name: pymultifracs
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8,<3.12.0
  - numpy>=1.22.4
  - scipy>=1.8.1
  - pywavelets>=1.3.0
  - seaborn>=0.12.0
  - scikit-learn>=1.1.1
  - statsmodels
  - pip
  - pip:
    - recombinator